# Generated by Django 5.2.8 on 2025-11-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bouquets/')),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('bouquet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleur.bouquet')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='fleur.distributor')),
            ],
            options={
                'unique_together': {('distributor', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inserted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'En attente paiement'), ('PAID', 'Payée'), ('VENDING', 'Distribution en cours'), ('COMPLETED', 'Terminée'), ('FAILED', 'Échec')], default='PENDING_PAYMENT', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='fleur.distributor')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleur.slot')),
            ],
        ),
    ]
